[package]
name = "automatic-octo-guacamole"
version = "1.0.12-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
